### ISSUE TITLE
Can't shutdown

### ISSUE THREAD

**Issue by urufudev** [karengharibyan/asus-z370-big-sur-opencore-efi#1]
Hi, when i shutdow, the hackintosh reboot
i have asus maximus x hero

**Comment by karengharibyan** [comment]
Hi. change ssdt to your motherboard

**Comment by urufudev** [comment]
> Hi. change ssdt to your motherboard

Hi, 
thanks for answering
I have the same motherboard
Asus Maximus X Hero
Or maybe you recommend a guide or tutorial
Thank you so much
